# Generated by Django 3.2.4 on 2021-08-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_auto_20210802_1427'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='state',
            field=models.CharField(choices=[('PU', 'Published'), ('DR', 'Draft'), ('UN', 'Unlisted'), ('PR', 'Private')], default='DR', max_length=2),
        ),
    ]
